services:
  nomad: 
    image: hashicorp/nomad:1.6.0-rc.1
    command: ["agent", "-dev", "-bind", "0.0.0.0"]
    ports:
      - "4646:4646"
    cap_add:
      - ALL
    privileged: true
    volumes:
      - /var/run/docker.sock.raw:/var/run/docker.sock
